config/routes.rb
Crawler::Application.routes.draw do
  resources :results

  resources :configurations

end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  has_many :results
  scope :activated, where(:active => true)
  def convert_sec_to_mins()
    secs = 0
    secs = self.time_ran unless self.time_ran.blank?
    hours = secs/3600.to_i
    minutes = (secs/60 - hours * 60).to_i
    seconds = (secs - (minutes * 60 + hours * 3600))
    [hours,minutes,seconds]
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  # GET /configurations
  # GET /configurations.xml
  def index
    @configurations = Configuration.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @configurations }
    end
  end

  # GET /configurations/1
  # GET /configurations/1.xml
  def show
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/new
  # GET /configurations/new.xml
  def new
    @configuration = Configuration.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/1/edit
  def edit
    @configuration = Configuration.find(params[:id])
  end

  # POST /configurations
  # POST /configurations.xml
  def create
    @configuration = Configuration.new(params[:configuration])

    respond_to do |format|
      if @configuration.save
        format.html { redirect_to(@configuration, :notice => 'Configuration was successfully created.') }
        format.xml  { render :xml => @configuration, :status => :created, :location => @configuration }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /configurations/1
  # PUT /configurations/1.xml
  def update
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      if @configuration.update_attributes(params[:configuration])
        format.html { redirect_to(@configuration, :notice => 'Configuration was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /configurations/1
  # DELETE /configurations/1.xml
  def destroy
    @configuration = Configuration.find(params[:id])
    @configuration.destroy

    respond_to do |format|
      format.html { redirect_to(configurations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/_form.html.erb
<%= form_for(@configuration) do |f| %>
  <% if @configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@configuration.errors.count, "error") %> prohibited this configuration from being saved:</h2>

      <ul>
      <% @configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :ats %><br />
    <%= f.text_area :ats %>
  </div>
  <div class="field">
    <%= f.label :duns %><br />
    <%= f.text_area :duns %>
  </div>
  <div class="field">
    <%= f.label :map_frequency %><br />
    <%= f.text_area :map_frequency %>
  </div>
  <div class="field">
    <%= f.label :map_day_of_week %><br />
    <%= f.text_area :map_day_of_week %>
  </div>
  <div class="field">
    <%= f.label :last_run %><br />
    <%= f.date_select :last_run %>
  </div>

  <div class="field">
    <%= f.label :no_of_times_run %><br />
    <%= f.text_field :no_of_times_run %>
  </div>
  <div class="field">
    <%= f.label :first_time %><br />
    <%= f.check_box :first_time %>
  </div>
  <div class="field">
    <%= f.label :has_next %><br />
    <%= f.check_box :has_next %>
  </div>
  <div class="field">
    <%= f.label :job_listing_option %><br />
    <%= f.text_area :job_listing_option %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :save_path %><br />
    <%= f.text_area :save_path %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_area :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_area :password %>
  </div>
  <div class="field">
    <%= f.label :worker %><br />
    <%= f.text_area :worker %>
  </div>
  <div class="field">
    <%= f.label :create_csv %><br />
    <%= f.check_box :create_csv %>
  </div>
  <div class="field">
    <%= f.label :job_name %><br />
    <%= f.check_box :job_name %>
  </div>
  <div class="field">
    <%= f.label :working_title %><br />
    <%= f.check_box :working_title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.check_box :location %>
  </div>
  <div class="field">
    <%= f.label :organization_name %><br />
    <%= f.check_box :organization_name %>
  </div>
  <div class="field">
    <%= f.label :department_description %><br />
    <%= f.check_box :department_description %>
  </div>

  <div class="field">
    <%= f.label :brieff_description %><br />
    <%= f.check_box :brieff_description %>
  </div>
  <div class="field">
    <%= f.label :detailed_description %><br />
    <%= f.check_box :detailed_description %>
  </div>
  <div class="field">
    <%= f.label :job_requirments %><br />
    <%= f.check_box :job_requirments %>
  </div>
  <div class="field">
    <%= f.label :addition_details %><br />
    <%= f.check_box :additional_details %>
  </div>
  <div class="field">
    <%= f.label :how_to_apply %><br />
    <%= f.check_box :how_to_apply %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.check_box :link %>
  </div>
  <div class="field">
    <%= f.label :save_html_blob %><br />
    <%= f.check_box :save_html_blob %>
  </div>
  <div class="field">
    <%= f.label :save_html_file %><br />
    <%= f.check_box :save_html_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configurations/edit.html.erb
<h1>Editing configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @configuration %> |
<%= link_to 'Back', configurations_path %>

app/views/configurations/index.html.erb
<h1>Listing configurations</h1>

<table>
  <tr>
    <th>Company name</th>
    <th>Ats</th>
    <th>Duns</th>
    <th>Map frequency</th>
    <th>Map day of week</th>
    <th>Last run</th>
    <th>No of times run</th>
    <th>First time</th>
    <th>Has next</th>
    <th>Job listing option</th>
    <th>Active</th>
    <th>Save path</th>
    <th>Title</th>
    <th>Url</th>
    <th>Login</th>
    <th>Password</th>
    <th>Worker</th>
    <th>Create csv</th>
    <th>Job name</th>
    <th>Working title</th>
    <th>Location</th>
    <th>Organization name</th>
    <th>Department description</th>
    <th>Brieff description</th>
    <th>Detailed description</th>
    <th>Job requirments</th>
    <th>Addition details</th>
    <th>How to apply</th>
    <th>Link</th>
    <th>Save html blob</th>
    <th>Save html file</th>
    <th>Time Ran (HH::MM::SS)</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @configurations.each do |configuration| %>
  <tr>
    <td><%= configuration.company_name %></td>
    <td><%= configuration.ats %></td>
    <td><%= configuration.duns %></td>
    <td><%= configuration.map_frequency %></td>
    <td><%= configuration.map_day_of_week %></td>
    <td><%= configuration.last_run %></td>
    <td><%= configuration.no_of_times_run %></td>
    <td><%= configuration.first_time %></td>
    <td><%= configuration.has_next %></td>
    <td><%= configuration.job_listing_option %></td>
    <td><%= configuration.active %></td>
    <td><%= configuration.save_path %></td>
    <td><%= configuration.title %></td>
    <td><%= configuration.url %></td>
    <td><%= configuration.login %></td>
    <td><%= configuration.password %></td>
    <td><%= configuration.worker %></td>
    <td><%= configuration.create_csv %></td>
    <td><%= configuration.job_name %></td>
    <td><%= configuration.working_title %></td>
    <td><%= configuration.location %></td>
    <td><%= configuration.organization_name %></td>
    <td><%= configuration.department_description %></td>
    <td><%= configuration.brieff_description %></td>
    <td><%= configuration.detailed_description %></td>
    <td><%= configuration.job_requirments %></td>
    <td><%= configuration.additional_details %></td>
    <td><%= configuration.how_to_apply %></td>
    <td><%= configuration.link %></td>
    <td><%= configuration.save_html_blob %></td>
    <td><%= configuration.save_html_file %></td>
    <td><%= sprintf("%02d:%02d:%02d\n", configuration.convert_sec_to_mins[0], configuration.convert_sec_to_mins[1], configuration.convert_sec_to_mins[2]) %></td>
    
    <td><%= link_to 'Show', configuration %></td>
    <td><%= link_to 'Edit', edit_configuration_path(configuration) %></td>
    <td><%= link_to 'Destroy', configuration, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Configuration', new_configuration_path %>

app/views/configurations/new.html.erb
<h1>New configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', configurations_path %>

app/views/configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @configuration.company_name %>
</p>

<p>
  <b>Ats:</b>
  <%= @configuration.ats %>
</p>

<p>
  <b>Duns:</b>
  <%= @configuration.duns %>
</p>

<p>
  <b>Map frequency:</b>
  <%= @configuration.map_frequency %>
</p>

<p>
  <b>Map day of week:</b>
  <%= @configuration.map_day_of_week %>
</p>

<p>
  <b>Last run:</b>
  <%= @configuration.last_run %>
</p>

<p>
  <b>No of times run:</b>
  <%= @configuration.no_of_times_run %>
</p>

<p>
  <b>First time:</b>
  <%= @configuration.first_time %>
</p>

<p>
  <b>Has next:</b>
  <%= @configuration.has_next %>
</p>

<p>
  <b>Job listing option:</b>
  <%= @configuration.job_listing_option %>
</p>

<p>
  <b>Active:</b>
  <%= @configuration.active %>
</p>

<p>
  <b>Save path:</b>
  <%= @configuration.save_path %>
</p>

<p>
  <b>Title:</b>
  <%= @configuration.title %>
</p>

<p>
  <b>Url:</b>
  <%= @configuration.url %>
</p>

<p>
  <b>Login:</b>
  <%= @configuration.login %>
</p>

<p>
  <b>Password:</b>
  <%= @configuration.password %>
</p>

<p>
  <b>Worker:</b>
  <%= @configuration.worker %>
</p>

<p>
  <b>Create csv:</b>
  <%= @configuration.create_csv %>
</p>

<p>
  <b>Job name:</b>
  <%= @configuration.job_name %>
</p>

<p>
  <b>Working title:</b>
  <%= @configuration.working_title %>
</p>

<p>
  <b>Location:</b>
  <%= @configuration.location %>
</p>

<p>
  <b>Organization name:</b>
  <%= @configuration.organization_name %>
</p>

<p>
  <b>Department description:</b>
  <%= @configuration.department_description %>
</p>

<p>
  <b>Brieff description:</b>
  <%= @configuration.brieff_description %>
</p>

<p>
  <b>Detailed description:</b>
  <%= @configuration.detailed_description %>
</p>

<p>
  <b>Job requirments:</b>
  <%= @configuration.job_requirments %>
</p>

<p>
  <b>Addition details:</b>
  <%= @configuration.additional_details %>
</p>

<p>
  <b>How to apply:</b>
  <%= @configuration.how_to_apply %>
</p>

<p>
  <b>Link:</b>
  <%= @configuration.link %>
</p>

<p>
  <b>Save html blob:</b>
  <%= @configuration.save_html_blob %>
</p>

<p>
  <b>Save html file:</b>
  <%= @configuration.save_html_file %>
</p>


<%= link_to 'Edit', edit_configuration_path(@configuration) %> |
<%= link_to 'Back', configurations_path %>