config/routes.rb
Crawler::Application.routes.draw do
  resources :results

  resources :configurations

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :configuration
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.xml
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @results }
    end
  end

  # GET /results/1
  # GET /results/1.xml
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @result }
    end
  end

  # GET /results/new
  # GET /results/new.xml
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.xml
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to(@result, :notice => 'Result was successfully created.') }
        format.xml  { render :xml => @result, :status => :created, :location => @result }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.xml
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to(@result, :notice => 'Result was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.xml
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to(results_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
        <% @result.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



 

  <div class="field">
    <%= f.label :job_name %><br />
    <%= f.text_area :job_name %>
  </div>
  <div class="field">
    <%= f.label :working_title %><br />
    <%= f.text_area :working_title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :organization_name %><br />
    <%= f.text_area :organization_name %>
  </div>
  <div class="field">
    <%= f.label :brieff_description %><br />
    <%= f.text_area :brieff_description %>
  </div>

  <div class="field">
    <%= f.label :detailed_description %><br />
    <%= f.text_area :detailed_description %>
  </div>

  <div class="field">
    <%= f.label :department_description %><br />
    <%= f.text_area :department_description %>
  </div>
  <div class="field">
    <%= f.label :job_requirments %><br />
    <%= f.text_area :job_requirments %>
  </div>
  <div class="field">
    <%= f.label :additional_details %><br />
    <%= f.text_area :additional_details %>
  </div>
  <div class="field">
    <%= f.label :how_to_apply %><br />
    <%= f.text_area :how_to_apply %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :html_blob %><br />
    <%= f.text_field :html_blob %>
  </div>
  <div class="field">
    <%= f.label :expired %><br />
    <%= f.check_box :expired %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Configuration</th>
    <th>Job Name</th>
    <th>Working title</th>
    <th>Location</th>
    <th>Organization name</th>
    <th>Brieff description</th>
    <th>Detailed description</th>
    <th>Department description</th>
    <th>Job requirments</th>
    <th>Additional details</th>
    <th>How to apply</th>
    <th>Link</th>
    <!--<th>Html blob</th>-->
    <th>Expired</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.configuration.title %></td>
    <td><%= result.job_name %></td>
    <td><%= result.working_title %></td>
    <td><%= result.location %></td>
    <td><%= result.organization_name %></td>
    <td><%= result.brieff_description %></td>
    <td><%= result.detailed_description %></td>
    <td><%= result.department_description %></td>
    <td><%= result.job_requirments %></td>
    <td><%= result.additional_details %></td>
    <td><%= result.how_to_apply %></td>
    <td><%= result.link %></td>
    <!--<td>Html blob<%#= result.html_blob %></td>-->
    <td><%= result.expired %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Configuration:</b>
  <%= @result.configuration_id %>
</p>

<p>
  <b>Expired:</b>
  <%= @result.expired %>
</p>

<p>
  <b>Job name:</b>
  <%= @result.job_name %>
</p>

<p>
  <b>Working title:</b>
  <%= @result.working_title %>
</p>

<p>
  <b>Location:</b>
  <%= @result.location %>
</p>

<p>
  <b>Organization name:</b>
  <%= @result.organization_name %>
</p>

<p>
  <b>Brieff description:</b>
  <%= @result.brieff_description %>
</p>

<p>
  <b>Detailed description:</b>
  <%= @result.detailed_description %>
</p>

<p>
  <b>Department description:</b>
  <%= @result.department_description %>
</p>

<p>
  <b>Job requirments:</b>
  <%= @result.job_requirments %>
</p>

<p>
  <b>Additional details:</b>
  <%= @result.additional_details %>
</p>

<p>
  <b>How to apply:</b>
  <%= @result.how_to_apply %>
</p>

<p>
  <b>Link:</b>
  <%= @result.link %>
</p>

<p>
  <b>Html blob:</b>
  <%= @result.html_blob %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>